### ISSUE TITLE
Automated Tests 

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Leviathan-Logic-Engine#16]
Automated tests prevent SceneTransitionTests from running in Unity.
Solution: Comment out [Ignore] line. 

To retain human interactivity in Unity while still allowing automation the line containing the [Ignore] command of SceneTransitionTests will be commented out during local testing and uncommented during pull requests.

**Comment by divark** [comment]
A workaround for the time being would be to comment out the `Ignore` attribute at the top of `SceneTransitionTests` locally.

Alternatively, a long-term solution would be to replace the `Ignore` attribute with the `Timeout` one instead, as [shown here](https://docs.nunit.org/articles/nunit/writing-tests/attributes/timeout.html), where we'd have it wait for no longer than, say, 15 seconds for these tests before they would move on.
