### ISSUE TITLE
As a developer, I want the repository to have more publicity.

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Leviathan-Logic-Engine#4]
- [x] Setup Project Board
- [x] Automate Building & Testing Process

**Comment by Exonoesis** [comment]
- [ ]

**Comment by divark** [comment]
- [ ] Write a task list
- [ ] Modify an item to say it's done

**Comment by Exonoesis** [comment]
- [ ] Item 1

**Comment by Exonoesis** [comment]
- [ ] Automate Building Process
