### ISSUE TITLE
As a developer, I want the code base to be clear, concise, and organized.

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Leviathan-Logic-Engine#5]
- [x] Exonoesis sweep of all files
- [x] Divark sweep of all files

**Comment by divark** [comment]
What to observe in the code:
- One-liner methods that could be combined into a bigger method.
- New features that made old work-in-progress implementations obsolete.
- Consistency violations with respect to Naming, such as Class Names (BackgroundViewer, DialogueViewer, ...), and methods (Frequently used method names for Getters/Setters should become the norm).
