### ISSUE TITLE
As a player, I want characters to be visible within Cutscenes.

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Leviathan-Logic-Engine#6]
- [x] Create Character prefabs
- [x] Create Character State, (SpeakerName, Dialogue), ()
- [x] Restructure Cutscenes to take in a touple as parameter

**Comment by divark** [comment]
Here's what comes to mind so far:

### Approach 1: Characters belong to the Asset Panel
![Approach1](https://user-images.githubusercontent.com/9102684/111400801-4d43e680-8685-11eb-8a49-6c4120a3d4c5.png)

#### Pros
- Character assets have same options of change from Asset Viewer.
- All Assets benefit from these changes (Emote/Animate, Move).
- Minimal ripple effect towards other components.
#### Cons
- Asset Viewer gets bigger.
- Character size must be kept in mind when positioning in Asset Viewer.

### Approach 2: Characters have their own panel
![Approach2](https://user-images.githubusercontent.com/9102684/111400802-503ed700-8685-11eb-81c0-4a6f174ed6c3.png)

#### Pros
- Character can be loaded in similar to Background Viewer = Sizing not as big of an issue.
- Character-specific logic kept coupled with Characters only (Possibly introducing Character Viewer)
  - Sizing/placement can be handled exclusively in Character Viewer if necessary = Less upfront setup.
#### Cons
- Mouse Listeners must now be aware of the Character Panel/Viewer.
  - Alternative: Asset Viewer must know of Character Panel -> Asset Viewer becomes more complex.
- Duplication of logic if other types of Assets can, say, move.
- Another panel/viewer to consider = More cognitive load.

**Comment by Exonoesis** [comment]
Approach 1 is looking the best to me. I already have plans to use some of the features from AssetViewer (dimming) on Characters and vice versa (move/animate/idle) on Assets, so Characters being attached to the AssetViewer and the AssetPanel would be beneficial on many levels. 

In addition, the AssetPanel is currently unused during Cutscenes which is when I would want to display Characters, thus I feel the AssetPanel would be more fully utilized with Approach 1. While I'm also concerned about AssetViewer getting larger, I don't see anything else being added to it after this feature so I think it's a non-issue in this case.

I'm not entirely sure what we mean in regards to Character size as the aspect ratio would be maintained from the created prefabs, it would only be a matter of positioning, which would be the case with either approach.

**Comment by divark** [comment]
Ah, I see. Well, in that case, I take back my comment on sizing.

Given that the first approach is appealing, here are a few questions:

- How would a new State be configured to fulfill this feature?
- What existing logic can be reused?
- What logic must be introduced, and where?
    - For instance, will there be new methods in this Character State? How about Asset Viewer?
- In testing, what should we expect to see versus the current state of the project?

**Comment by Exonoesis** [comment]
`How would a new State be configured to fulfill this feature?`
Characters would not be mouse reactive at this point in development. Thus OnMouseEnter, OnMouseExit, and Click would be empty functions. Queries such as isClicked and getNextScene would return nothing. The State will also need at the very least two arrays to hold body and facial expression sprites respectively.

`What existing logic can be reused?`
As previously stated, the Dim and Lighten functions from AssetViewer will be utilized for Characters. Additionally, Characters can either be instantiated from AssetViewer or created as CoreAssets and the track feature used. I would suggest we define them as CoreAssets on the assumption that Characters should only be created once and then hidden/shown as needed.

`What logic must be introduced, and where?`
Assuming Characters are CoreAssets, then their State will need to have a query for an Active bool to control visibility in Scenes. Additionally, there should be a Speaker bool to control dimming and lightening when the specific character isn't/is the current speaker. These sprites can be read from the prefab for initialization and then accessed by index and handed to a function in AssetViewer to handle image transitions. This brings me to needing said function in AssetViewer. For generalization purposes, I suggest this function takes in an asset and a sprite to transition to.

`In testing, what should we expect to see versus the current state of the project?`
A full test of discussed functionality should include the following
- Creating an Asset with the Character State that appears on the screen in a designated location
- Dimming when the Character is not the active speaker and Lightening when they are
- Showing and hiding when appropriate
- Swapping seamlessly between various body sprites and facial expression sprites

**Note**
I've decided that moving an Asset is not within the scope of this feature as it's not required at this time.

**Comment by divark** [comment]
While I understand that Characters should only be initialized once to avoid redundancy, Core Assets are reserved for Assets such as Menu Buttons, and primary UI functionality (Think DialogueViewer's Nav Button, and the History button in the future).

Therefore, I recommend keeping Characters as a Scene Asset to prevent unnecessary sharing among Cutscenes that should already be distinct as is.

**Comment by Exonoesis** [comment]
A majority of Cutscenes will require at least one Character Asset, that's a lot of instanciating the same prefab in the exact same position. I'd like to avoid that if possible. I would prefer Characters to either be considered Core Assets or to have a separate Character Assets that are static, as Core Assets are.

**Comment by divark** [comment]
Ah, okay, so it's a matter of keeping the number of instantiations low. I can work with that.

Just to be sure though, isn't that the point of the `basePrefabs` variable in AssetViewer?

Also, I found a discussion regarding the [costs of instantiations](https://forum.unity.com/threads/is-instantiate-bad-for-performance-unity-says-its-fast-forums-say-its-slow.182560/) here if you're interested.

**Comment by Exonoesis** [comment]
The point of `basePrefabs` is so that we have a reference for the prefab we're instantiating. Every time we instantiate an Asset we're cloning a prefab and placing the clone in the Scene. While I agree that instantiations aren't the worst for performance, even in the linked forum post one person says "if the game is really small or simple enough, keep gameobjects hidden until you need them, that way you already have them in the scene."

In the case of the main character Asset, it will appear in almost every single Cutscene and almost always in the same position (most likely on the left side of the screen.) Every game will also have a limited cast of characters - in the case of Helping Hand about 20 - so it isn't as if we're holding onto hundreds of hidden Assets. Additionally, due to the nature of storytelling, the same characters will appear in multiple Scenes in rather quick succession.  

I do see the concern and the logic behind keeping Scenes self-contained, but the way I see it either a Cutscene references the Characters it needs and asks the AssetViewer to instantiate them, or it asks the AssetViewer to display the Characters that it needs which already exist. Either way, the Cutscene still has a way to invoke what is required of it.

I could see a compromise in which we held a character Asset around until that character left the plot so to speak - such as in the event of the character leaving the party - at which point the Asset could be destroyed and re-instantiating later on, but I feel this would increase cognitive load for the game creator.

**Comment by divark** [comment]
Given that we’re dealing with 2D games for the time being, this seems like an pre-optimization that will result in more complexity to the engine itself than necessary.

It could be said that even with a limited cast of characters in some game, the odds of them needing to be persistent throughout the entirety of the game are lower. The only set of elements that need this level of optimization are UI elements, since 99% of the time they will be visible. Cutscenes, let alone Characters, do not share this.

If there was concern that this would cause a performance issue, then it’d be appropriate to use caching. However, instantiating has very little performance impact as mentioned previously, thus the desire to keep it simple. If we wanted to promote great reuse on assets and its sub parts coming in, then we would have to address backgrounds being consistent as well for some sequence of Cutscenes in the same setting. For both of these though, what are the benefits gained from this from a performance point of view, given that 2D rendering is trivial?

Now, #14 would be a good candidate for this level of optimization, as ECS is designed with this granular amount of efficiency in mind.

I think it’s important to consider how Cutscenes will change with this feature. 

Another approach is that a Cutscene upon construction takes an Asset, and an optional background. The Asset supplies the Character State, which stores who’s speaking, and what’s their portrait at that moment. The State would hand off the appropriate info now to both Asset Viewer, and the Dialogue Viewer, similar to how buttons were created recently. 
Note that a portrait is not an accumulation of bodies and expressions anymore. This would lead to more images for a set of characters, but something like sprite sheets come to mind as well. Not only that, but Unity is capable of rendering animated textures if I recall correctly.

Do these make sense, both the reasoning and this other approach?

**Comment by Exonoesis** [comment]
Backgrounds are already optimized in that they are persistent between scenes if the same Background is used sequentially. I do see and understand what you're saying, however. I agree that this level of optimization is unnecessary and that the logic to manage what I'm suggesting would add complexity. So the matter then becomes when to instantiate and how to go about it.

I do like the approach of handing a Character (or two, or none) to the Cutscene at construction. It makes sense and feels natural to pair the dialogue and speaker with a Character portrait. I do have inflation concerns with the number of files when it comes to making these fixed images, however. Even with the use of a sprite sheet, an artist has to make that sheet and export each combination of body and facial expression. That could easily multiply to an unmanageable size. I would still recommend an array of some sort to prevent exponential growth of the sprite sheet.

That being said, the clone of the prefab will contain every sprite in the sprite sheet by default and there isn't a way I know of to specify which individual sprite to access without mapping all of them to an array and knowing the index of the desired sprite.

**Comment by Exonoesis** [comment]
As per our recent private discussion.

Character Assets shall be defined as a single sprite displayed on the `AssetPanel`. Multi-layer character images are a level of complexity that need not be handled by the LLE. If they are to be accommodated at a later date then it will be done via external tools.

The logic of `Speaker` and `Dialogue` will be moved out of `Cutscene` and into the Character `State` of an Asset as it logically makes sense that these should be packaged with a character portrait. `Cutscene` will then be restructured to take in two Assets as parameters coupled as a touple. The first Asset, as defined as the left half of the touple, will be the "speaker" in the `Scene` and will hold the

**Comment by Exonoesis** [comment]
Oops
